ALTER TABLE LANCAMENTOS_MENSAIS DROP CONSTRAINT IF EXISTS FK_LANCAMENTOS_MENSAIS_ORCAMENTO_ID__ID;

ALTER TABLE LANCAMENTOS_MENSAIS ADD CONSTRAINT FK_LANCAMENTOS_MENSAIS_ORCAMENTO_ID__ID 
    FOREIGN KEY (ORCAMENTO_ID) REFERENCES ORCAMENTOS_MENSAIS(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ORCAMENTOS_MENSAIS ADD COLUMN IF NOT EXISTS SEQ_RECEITA INT NOT NULL DEFAULT 0;
ALTER TABLE ORCAMENTOS_MENSAIS ADD COLUMN IF NOT EXISTS SEQ_DESPESA INT NOT NULL DEFAULT 0;

ALTER TABLE ORCAMENTOS_MENSAIS ALTER COLUMN SLUG TYPE VARCHAR(8);
