CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID BIGSERIAL PRIMARY KEY,
    USUARIO_ID BIGINT NOT NULL,
    NOME VARCHAR(16) NOT NULL,
    ICONE VARCHAR(16) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE CATEGORIAS ADD CONSTRAINT uk_categoria_usuario_nome UNIQUE (USUARIO_ID, NOME);
