CREATE TABLE IF NOT EXISTS LANCAMENTOS_FIXOS (
    ID BIGSERIAL PRIMARY KEY,
    USUARIO_ID BIGINT NOT NULL,
    TIPO VARCHAR(16) NOT NULL,
    DIA_VENCIMENTO INT NOT NULL,
    MES_INICIO VARCHAR(6) NOT NULL,
    FORMA_PAGAMENTO VARCHAR(16) NOT NULL,
    CARTAO_ID BIGINT NULL,
    CATEGORIA_ID BIGINT NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CRIADO_EM TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP NOT NULL,
    EXCLUIDO_EM VARCHAR(6) NULL,
    CONSTRAINT FK_LANCAMENTOS_FIXOS_CATEGORIA_ID__ID
        FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE LANCAMENTOS_FIXOS ADD CONSTRAINT ck_lancamentos_fixos_tipo
    CHECK (TIPO IN ('RECEITA', 'DESPESA'));

ALTER TABLE LANCAMENTOS_FIXOS ADD CONSTRAINT ck_lancamentos_fixos_dia_vencimento
    CHECK (DIA_VENCIMENTO BETWEEN 1 AND 31);

ALTER TABLE LANCAMENTOS_FIXOS ADD CONSTRAINT ck_lancamentos_fixos_forma_pagamento
    CHECK (FORMA_PAGAMENTO IN ('BOLETO', 'PIX', 'CARTAO'));

ALTER TABLE LANCAMENTOS_FIXOS ADD CONSTRAINT ck_lancamentos_fixos_cartao
    CHECK (
        (FORMA_PAGAMENTO = 'CARTAO' AND CARTAO_ID IS NOT NULL)
        OR (FORMA_PAGAMENTO <> 'CARTAO' AND CARTAO_ID IS NULL)
    );
