ALTER TABLE LANCAMENTOS_FIXOS
    ADD COLUMN DESCRICAO VARCHAR(32) NOT NULL DEFAULT 'Lancamento fixo',
    ADD COLUMN VALOR DECIMAL(10, 2) NOT NULL DEFAULT 0.00;

ALTER TABLE LANCAMENTOS_FIXOS
    ALTER COLUMN DESCRICAO DROP DEFAULT,
    ALTER COLUMN VALOR DROP DEFAULT;
