CREATE TABLE IF NOT EXISTS CARTOES (
    ID BIGSERIAL PRIMARY KEY,
    USUARIO_ID BIGINT NOT NULL,
    NOME VARCHAR(16) NOT NULL,
    ICONE VARCHAR(16) NOT NULL,
    COR CHAR(7) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CRIADO_EM TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP NOT NULL
);

ALTER TABLE CARTOES ADD CONSTRAINT ck_cartoes_cor
    CHECK (COR ~ '^#[0-9A-Fa-f]{6}$');
