CREATE TABLE IF NOT EXISTS PARCELAMENTOS (
    ID BIGSERIAL PRIMARY KEY,
    CARTAO_ID BIGINT NOT NULL,
    NOME VARCHAR(32) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    PARCELAS INT NOT NULL,
    MES_INICIO VARCHAR(6) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CRIADO_EM TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP NOT NULL,
    EXCLUIDO_EM TIMESTAMP NULL,
    CONSTRAINT FK_PARCELAMENTOS_CARTAO_ID__ID
        FOREIGN KEY (CARTAO_ID) REFERENCES CARTOES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE PARCELAMENTOS ADD CONSTRAINT ck_parcelamentos_parcelas
    CHECK (PARCELAS > 0);

ALTER TABLE PARCELAMENTOS ADD CONSTRAINT ck_parcelamentos_mes_inicio
    CHECK (MES_INICIO ~ '^\\d{6}$');
