CREATE TABLE IF NOT EXISTS FATURAS (
    ID BIGSERIAL PRIMARY KEY,
    CARTAO_ID BIGINT NOT NULL,
    LANCAMENTO_ID BIGINT NOT NULL UNIQUE,
    VALOR DECIMAL(10, 2) NOT NULL,
    MES VARCHAR(6) NOT NULL,
    CRIADO_EM TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP NOT NULL,
    CONSTRAINT FK_FATURAS_CARTAO_ID__ID
        FOREIGN KEY (CARTAO_ID) REFERENCES CARTOES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_FATURAS_LANCAMENTO_ID__ID
        FOREIGN KEY (LANCAMENTO_ID) REFERENCES LANCAMENTOS_MENSAIS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE FATURAS ADD CONSTRAINT ck_faturas_mes
    CHECK (MES ~ '^\d{6}$');

ALTER TABLE LANCAMENTOS_MENSAIS ADD COLUMN FATURA_ID BIGINT NULL;
ALTER TABLE LANCAMENTOS_MENSAIS ADD CONSTRAINT FK_LANCAMENTOS_MENSAIS_FATURA_ID__ID
    FOREIGN KEY (FATURA_ID) REFERENCES FATURAS(ID) ON DELETE SET NULL ON UPDATE RESTRICT;